/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.*;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;
import sisxp.*;

/**
 *
 * @author Yeah
 */
public class PlanillaDeGastos extends javax.swing.JFrame {
    private GestorGastos gastos;

    /**
     * Creates new form PlanillaGastos
     */
    public PlanillaDeGastos() {
        gastos = new GestorGastos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGastos = new javax.swing.JTable();
        botonInsertar = new javax.swing.JButton();
        botonActualizar = new JButton();
        botonAtras = new JButton();
        botonInsertar.addActionListener(new OyenteBoton());
        botonActualizar.addActionListener(new OyenteActualizar());
        botonAtras.addActionListener(new OyenteAtras());
        panelCheck = new JPanel();
        panelCheck.setLayout(new FlowLayout());
        ArrayList<String> tiposExistentes = gastos.tiposExistentes();
        int num = tiposExistentes.size();
        cuadraditos = new JCheckBox[num];
        for(int i = 0; i < num; i++)
        {
            cuadraditos[i] = new JCheckBox();
            cuadraditos[i].setText(tiposExistentes.get(i));
            panelCheck.add(cuadraditos[i]);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        llenarGastos();
        
        jScrollPane1.setViewportView(tablaGastos);

        botonInsertar.setText("Nuevo Gasto");
        botonActualizar.setText("Actualizar");
        botonAtras.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(botonInsertar)
                    .addGroup(layout.createSequentialGroup())
                        .addGap(91, 91, 91)
                        .addComponent(botonActualizar)
                    .addGroup(layout.createSequentialGroup())
                        .addGap(0, 0, 0)
                        .addComponent(panelCheck)
                    .addGroup(layout.createSequentialGroup())
                        .addGap(0,0,0)
                        .addComponent(botonAtras)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonInsertar)
                .addGap(100, 100, 100)
                .addComponent(botonActualizar)
                .addGap(0, 0, 0)
                .addComponent(panelCheck)
                .addGap(0, 0, 0)
                .addComponent(botonAtras)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    class OyenteBoton implements ActionListener
    {
        public void actionPerformed(ActionEvent e){
            
             gastos.formulario();
        }
    }
    
    class OyenteActualizar implements ActionListener
    {
        public void actionPerformed(ActionEvent e){
            
             llenarGastos();
        }
    }
    
    class OyenteAtras implements ActionListener
    {
        public void actionPerformed(ActionEvent e){
            MainPage m = new MainPage();
            m.setVisible(true);
             setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanillaDeGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanillaDeGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanillaDeGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanillaDeGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {*/
                new PlanillaDeGastos().setVisible(true);/*
            }
        });*/
    }
    
    private String[][] llenarGastos()
    {
        
        ArrayList<String[]> lista;
        int numCheckeados = 0;
        for(int i = 0; i < cuadraditos.length; i++)
        {
            if(cuadraditos[i].isSelected())
            {
                numCheckeados++;
            }else{}
        }
        if(numCheckeados == 0)
        {
        lista = gastos.getGastos();
        }else
        {
            String[] checkeados = new String[numCheckeados];
            int j = 0;
            for(int i = 0; i < cuadraditos.length && j < numCheckeados; i++)
            {
                if(cuadraditos[i].isSelected())
                {
                    String aux = cuadraditos[i].getText();
                    checkeados[j] = aux;
                    j++;
                }else{}
            }
            lista = gastos.getGastos(checkeados);
        }
        String[][] res = new String[lista.size()][7];
        for(int i = 0; i < lista.size(); i++)
        {
            for(int j = 0; j < 7; j++)
            {
                res[i][j] = lista.get(i)[j];
            }
        }
        
        tablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            res,
            new String [] {
                "Numero", "Tipo de Gasto", "Gasto", "Responsable", "Fecha", "Detalle", "Monto"
            }
        ));
        return res;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonInsertar;
    private javax.swing.JTable tablaGastos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox[] cuadraditos;
    private JButton botonActualizar;
    private JButton botonAtras;
    private JPanel panelCheck;
    // End of variables declaration                   
}
